language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - leesaac2@gmail.com

#before_deploy:
#  - zip -r springboot2-webservice *
#  - mkdir -p deploy
#  - mv springboot2-webservice.zip deploy/springboot2-webservice.zip
#
#deploy:
#  -provider: s3
#  access_key_id: $AWS_ACCESS_KEY # Travis repo setting
#  secret_access_key: $AWS_SECRET_KEY # Travis repo setting
#
#  bucket: yisak-springboot2-webservice-build
#  region: ap-northeast-2
#  skip_cleanup: true
#  acl: private # zip 파일접근을 private로
#  local_dir: deploy #before_deploy에서 생성한 디렉토리
#  wait-until-deployed: true
